name: gdsc_lnct
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.0.1
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  convex_bottom_bar: ^3.0.0
  cloud_firestore: ^2.5.1
  firebase_core: ^1.6.0
  lottie: ^1.1.0
  provider: ^6.0.0
  font_awesome_flutter: ^9.1.0
  dotted_line: ^3.0.0
  url_launcher: ^6.0.9
  sliding_up_panel: ^2.0.0+1
  dashed_circle: ^0.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  firebase_storage: ^10.0.3
  flutter_blurhash: ^0.6.0
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0
  firebase_messaging: ^10.0.6
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  flutter_local_notifications: ^8.1.1+2
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0


flutter_native_splash :
  color: "#FFFFFF"
  image: assets/splashScreen.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launchicon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - core members/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

